stages:
  - build_backend
  - deploy_backend

# 後端構建階段 - 僅構建 travel-services
build_backend:
  stage: build_backend
  image: maven:3.8.6-openjdk-11-slim
  script:
    - cd ticket-simulator-services/travel-services
    - mvn clean package -DskipTests -Pprod
  artifacts:
    paths:
      - ticket-simulator-services/travel-services/target/travel-services-0.0.1-SNAPSHOT.jar
  rules:
    - changes:
        - ticket-simulator-services/**/*

# 部署後端 - 僅部署 travel-services
deploy_backend:
  stage: deploy_backend
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync  # 安裝 SSH 和 rsync
    - mkdir -p ~/.ssh
    - echo "$EC2_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa  # 使用 GitLab CI 變數
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan ec2-98-84-135-86.compute-1.amazonaws.com >> ~/.ssh/known_hosts  # 將 EC2 加入 known_hosts
  script:
    # 將 JAR 文件複製到 EC2 實例
    - scp ticket-simulator-services/travel-services/target/travel-services-0.0.1-SNAPSHOT.jar ec2-user@ec2-98-84-135-86.compute-1.amazonaws.com:/opt/ticket-simulator-services/travel-services/travel-services-0.0.1-SNAPSHOT.jar
    # 重新啟動 systemd 服務
    - ssh ec2-user@ec2-98-84-135-86.compute-1.amazonaws.com "sudo systemctl restart travel-services"
  rules:
    - changes:
        - ticket-simulator-services/**/*