stages:
  - install_frontend
  - test_frontend
  - build_frontend
  - deploy_frontend

# 定義變數
variables:
    NODE_ENV: "development" # 只會包出 devDependencies
  # NODE_ENV: "production" # 只會包出 dependencies

# 快取依賴以加快構建速度
# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - ticket-simulator-web/node_modules/

# 安裝依賴
install_frontend:
  stage: install_frontend
  image: node:20
  script:
    - echo "=== 開始安裝依賴 ==="
    - cd ticket-simulator-web
    - npm install -g npm@8.19.1
    - npm install
    - npm list --depth=0
    - echo "=== 結束安裝依賴 ==="
  artifacts: # 保留指定的檔案或目錄，提供給其他 job 使用
    paths:
      - ticket-simulator-web/node_modules/

  # cache:
  #   paths:
  #     - ticket-simulator-web/node_modules/
  # artifacts:
  #   paths:
  #     - ticket-simulator-web/node_modules/
  only: # 指定在哪些情況下應該運行 CI/CD pipeline
    - main # 只有在 main 分支上提交代碼時才運行
    - merge_requests
    # 當 a 分支創建一個 merge request 合併到 main 分支時，GitLab CI/CD 會運行 a 分支的 CI/CD pipeline。
    # 這樣可以在合併之前對 a 分支的代碼進行測試和驗證，確保其不會引入錯誤或破壞現有功能。

# 運行測試
test_frontend:
  stage: test_frontend
  image: node:20
  script:
    - cd ticket-simulator-web
    - npm install -g npm@8.19.1
    - npm run test:unit
  dependencies:
    - install_dependencies
  only:
    - main
    - merge_requests

# 構建應用
build_frontend:
  stage: build_frontend
  image: node:20
  script:
    - cd ticket-simulator-web
    - npm install -g npm@8.19.1
    - npm run build
  artifacts:
    paths:
      - ticket-simulator-web/dist/
  dependencies:
    - install_dependencies
  only:
    - main
    - merge_requests

# 部署應用
deploy_frontend:
  stage: deploy_frontend
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync  # 安裝 SSH 和 rsync
    - mkdir -p ~/.ssh
    - echo "$EC2_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa  # 使用 GitLab CI 變數
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan ec2-98-84-135-86.compute-1.amazonaws.com >> ~/.ssh/known_hosts  # 將 EC2 加入 known_hosts
  script:
    - rsync -avz --delete ticket-simulator-web/dist/ ec2-user@ec2-98-84-135-86.compute-1.amazonaws.com:/usr/share/nginx/html/  # 替換為您的 EC2 公共 IP 或域名
  only:
    - main
  when: on_success